### ISSUE TITLE
Wrapping distance

### ISSUE THREAD

**Issue by rhomu** [rhomu/vicsek#1]
Implement wrapping euclidean distance for true periodic boundary conditions.

**Comment by zodiac911** [comment]
sorry to bother I am not so familiar with python but I want to use your code for a research and I get this error out, any idea about what may be the reason?

Traceback (most recent call last):
  File "vicsek.py", line 294, in <module>
    app.run()
  File "vicsek.py", line 252, in run
    self.flock.move()
  File "vicsek.py", line 166, in move
    b.move()
  File "vicsek.py", line 95, in move
    self.pos = [self.pos[0] % app.width, self.pos[1] % app.height]
TypeError: 'map' object is not subscriptable

**Comment by rhomu** [comment]
I can not reproduce your error. What version of Python are you using?

**Comment by rhomu** [comment]
(by the way you should have opened a different issue, but ok ;-) )

**Comment by zodiac911** [comment]
I'm using python 3.6.3

**Comment by zodiac911** [comment]
the whole result I'm getting from pycharm is as follows


"C:\Users\wang tao\AppData\Local\Programs\Python\Python36\python.exe" "C:/Users/wang tao/PycharmProjects/WTpy/main.py"
Traceback (most recent call last):
  File "C:/Users/wang tao/PycharmProjects/WTpy/main.py", line 294, in <module>
    app.run()
  File "C:/Users/wang tao/PycharmProjects/WTpy/main.py", line 252, in run
    self.flock.move()
  File "C:/Users/wang tao/PycharmProjects/WTpy/main.py", line 166, in move
    b.move()
  File "C:/Users/wang tao/PycharmProjects/WTpy/main.py", line 95, in move
    self.pos = [self.pos[0] % app.width, self.pos[1] % app.height]
TypeError: 'map' object is not subscriptable

Process finished with exit code 1

**Comment by rhomu** [comment]
Running with python 2 should solve your problem! (3 > version >= 2.7)

**Comment by zodiac911** [comment]
ok i will give it a go

**Comment by zodiac911** [comment]
I'm still getting the same error pop out after switching to python 2.7.14, by the way  I'm running this in windows, is this going to be a problem?

**Comment by zodiac911** [comment]
It runs ok now, thanks for your code

**Comment by rhomu** [comment]
Sure no problem! Enjoy!
